AWSTemplateFormatVersion: "2010-09-09"
Description: "Merlin Pipeline Management: Base Stack"
Parameters:
  Branch:
    Type: String
    AllowedValues:
    - master
    Default: master
    Description: The branch from which the the pipeline-management-project should be built
  App:
    Type: String
    AllowedValues:
    - merlin-pipeline-management
    Default: merlin-pipeline-management
  ArtifactBucket:
    Type: String
    AllowedValues:
    - appleforge-merlin-artifacts
    Default: appleforge-merlin-artifacts

Resources:
  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Test
      Name: /codepipeline/artifact-bucket
      Type: String
      Value: !Ref ArtifactBucket

  IamRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/iamroles.yml
      Parameters:
        Branch: !Ref Branch
        App: !Ref App
        ArtifactBucket: !Ref ArtifactBucket

  MerlinGatewayCICDPipelines:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: projects/merlin-gateway-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        ManagedApp: merlin-gateway
        CodeBuildRoleArn: !GetAtt IamRolesStack.Outputs.CodeBuildRoleArn
        CodePipelineRoleArn: !GetAtt IamRolesStack.Outputs.CodePipelineRoleArn
        CloudFormationDeployerRoleArn: !GetAtt IamRolesStack.Outputs.CloudFormationDeployerRoleArn

  MerlinPythonLayerCICDPipelines:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: projects/merlin-python-layer-pipeline.yml
      Parameters:
        ArtifactBucket: !Ref ArtifactBucket
        ManagedApp: merlin-python-layer
        CodeBuildRoleArn: !GetAtt IamRolesStack.Outputs.CodeBuildRoleArn
        CodePipelineRoleArn: !GetAtt IamRolesStack.Outputs.CodePipelineRoleArn
        CloudFormationDeployerRoleArn: !GetAtt IamRolesStack.Outputs.CloudFormationDeployerRoleArn
