AWSTemplateFormatVersion: "2010-09-09"
Description: "Merlin Pipeline Management: Master Stack"
Parameters:
  Branch:
    Type: String
    AllowedValues:
    - master
    - develop
    Default: master
  App:
    Type: String
    AllowedValues:
    - merlin-pipeline-management
    Default: merlin-pipeline-management
  ArtifactBucket:
    Type: String
    AllowedValues:
    - appleforge-merlin-artifacts
    Default: appleforge-merlin-artifacts

Resources:
#  Param:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Description: Test
#      Name: /codepipeline/artifact-bucket
#      Type: String
#      Value: !Ref ArtifactBucket

  IamRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: iamroles.yml
      Parameters:
        Branch: !Ref Branch
        App: !Ref App
        ArtifactBucket: !Ref ArtifactBucket

  MerlinPythonLayerPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: python-layer-pipeline.yml
      Parameters:
        Branch: !Ref Branch
        ArtifactBucket: !Ref ArtifactBucket
        ManagedApp: merlin-python-layer
        CodeBuildRoleArn: !GetAtt IamRolesStack.Outputs.CodeBuildRoleArn
        CodePipelineRoleArn: !GetAtt IamRolesStack.Outputs.CodePipelineRoleArn
        CloudFormationDeployerRoleArn: !GetAtt IamRolesStack.Outputs.CloudFormationDeployerRoleArn
        TemplatePath: aws-artifacts/cfn/layer.yml
        ParameterOverrides: |
          {
            "ArtifactBucket" : { "Fn::GetArtifactAtt" : ["BuildArtifact", "BucketName"]},
            "ArtifactKey" : { "Fn::GetArtifactAtt" : ["BuildArtifact", "ObjectKey"]}
          }

  MerlinGatewayPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn-and-lambda-pipeline.yml
      Parameters:
        Branch: !Ref Branch
        ArtifactBucket: !Ref ArtifactBucket
        ManagedApp: merlin-gateway
        CodeBuildRoleArn: !GetAtt IamRolesStack.Outputs.CodeBuildRoleArn
        CodePipelineRoleArn: !GetAtt IamRolesStack.Outputs.CodePipelineRoleArn
        CloudFormationDeployerRoleArn: !GetAtt IamRolesStack.Outputs.CloudFormationDeployerRoleArn
        TemplatePath: merlin-gateway-template.yml
        ParameterOverrides: |
          {
            "ArtifactBucket" : { "Fn::GetArtifactAtt" : ["BuildArtifact", "BucketName"]},
            "LambdaZipName" : "#{BuildVariables.LAMBDA_FILE_KEY}"
          }


